# Generated by Django 5.1.5 on 2025-01-28 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendPendingTask', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingtask',
            old_name='task_created_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='pendingtask',
            name='task_description',
        ),
        migrations.RemoveField(
            model_name='pendingtask',
            name='task_name',
        ),
        migrations.RemoveField(
            model_name='pendingtask',
            name='task_status',
        ),
        migrations.AddField(
            model_name='pendingtask',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción detallada de la tarea'),
        ),
        migrations.AddField(
            model_name='pendingtask',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Fecha límite de la tarea', null=True),
        ),
        migrations.AddField(
            model_name='pendingtask',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Urgente'), (2, 'Alta'), (3, 'Media'), (4, 'Baja')], default=2),
        ),
        migrations.AddField(
            model_name='pendingtask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='pendingtask',
            name='title',
            field=models.CharField(help_text='Título de la tarea', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pendingtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
