# Generated by Django 5.1.5 on 2025-02-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendPendingTask', '0002_rename_task_created_at_pendingtask_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtask',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Urgente'), (2, 'Alta'), (3, 'Media'), (4, 'Baja')], default=4),
        ),
    ]
