# Generated by Django 5.1.5 on 2025-02-05 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendPendingTask', '0003_alter_pendingtask_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_tasks', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
