# Generated by Django 5.1.5 on 2025-02-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendPendingTask', '0004_alter_pendingtask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completada')], default='PENDING', max_length=20),
        ),
    ]
